In [59]:
%pip install numpy

Note: you may need to restart the kernel to use updated packages.



[notice] A new release of pip available: 22.3 -> 22.3.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [60]:
%time
import numpy as np

temperature = [20.1, 20.1, 20.2, 20.4, 20.8, 30]
print(temperature)

t1 = temperature * 5

print(f"При множенні на 5 маємо: {t1}")

t1 = list()
for x in temperature:
    t1.append(x*5 + 20)

print(f"При множенні на 5 маємо: {t1}, тип даних {type(t1)}")

t1 = [ x*5 + 20 for x in temperature] 
print(f"Тепер отримаємо: {t1}") 

CPU times: total: 0 ns
Wall time: 0 ns
[20.1, 20.1, 20.2, 20.4, 20.8, 30]
При множенні на 5 маємо: [20.1, 20.1, 20.2, 20.4, 20.8, 30, 20.1, 20.1, 20.2, 20.4, 20.8, 30, 20.1, 20.1, 20.2, 20.4, 20.8, 30, 20.1, 20.1, 20.2, 20.4, 20.8, 30, 20.1, 20.1, 20.2, 20.4, 20.8, 30]
При множенні на 5 маємо: [120.5, 120.5, 121.0, 122.0, 124.0, 170], тип даних <class 'list'>
Тепер отримаємо: [120.5, 120.5, 121.0, 122.0, 124.0, 170]


In [61]:
t2 = np.array(temperature)
print("Масив з використанням методів NumPy", t2," тип даних ", type(t2))

t3 = t2 * 5 + 20
print("При множенні на 5 отримуємо:", t3)
t3 = t2 % 5
print("При множенні на 5 отримуємо:", t3)

Масив з використанням методів NumPy [20.1 20.1 20.2 20.4 20.8 30. ]  тип даних  <class 'numpy.ndarray'>
При множенні на 5 отримуємо: [120.5 120.5 121.  122.  124.  170. ]
При множенні на 5 отримуємо: [0.1 0.1 0.2 0.4 0.8 0. ]


In [62]:
ll = [1, 2, 3, 4, 5]
l2 = [6, 7, 8, 9, 10]
l3 = [11, 12, 13, 14, 15]
vector_1 = np.array(ll)
vector_2 = np.array([ll, l2, l3])
vector_3 = np.array([[ll, l2, l3], [ll, l2, l3],  [ll, l2, l3],  [ll, l2, l3]])

print(f"Це є List {ll}, Масив numpy \n {vector_1},\nМасив numpy \n {vector_2},\nМасив numpy \n {vector_3}")

t1 = vector_1 * 5
t2 = vector_2 * 5
t3 = vector_3 * 5
print(f"Масив numpy \n {t1},\nМасив numpy \n {t2},\nМасив numpy \n {t3}")

Це є List [1, 2, 3, 4, 5], Масив numpy 
 [1 2 3 4 5],
Масив numpy 
 [[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]],
Масив numpy 
 [[[ 1  2  3  4  5]
  [ 6  7  8  9 10]
  [11 12 13 14 15]]

 [[ 1  2  3  4  5]
  [ 6  7  8  9 10]
  [11 12 13 14 15]]

 [[ 1  2  3  4  5]
  [ 6  7  8  9 10]
  [11 12 13 14 15]]

 [[ 1  2  3  4  5]
  [ 6  7  8  9 10]
  [11 12 13 14 15]]]
Масив numpy 
 [ 5 10 15 20 25],
Масив numpy 
 [[ 5 10 15 20 25]
 [30 35 40 45 50]
 [55 60 65 70 75]],
Масив numpy 
 [[[ 5 10 15 20 25]
  [30 35 40 45 50]
  [55 60 65 70 75]]

 [[ 5 10 15 20 25]
  [30 35 40 45 50]
  [55 60 65 70 75]]

 [[ 5 10 15 20 25]
  [30 35 40 45 50]
  [55 60 65 70 75]]

 [[ 5 10 15 20 25]
  [30 35 40 45 50]
  [55 60 65 70 75]]]


In [63]:
print("\nВектор має розмір", vector_1.shape)
print("\nВектор має розмір", vector_2.shape)
print("\nВектор має розмір", vector_3.shape)


Вектор має розмір (5,)

Вектор має розмір (3, 5)

Вектор має розмір (4, 3, 5)


In [64]:
vector_row = np.array([[1, -5, 3, 2, 4]])
vector_column = np.array([[1], 
                          [2], 
                          [3], 
                          [4]])
print(vector_row, "\nВектор має розмір", vector_row.shape)
print(vector_column, "\nВектор має розмір", vector_column.shape)

[[ 1 -5  3  2  4]] 
Вектор має розмір (1, 5)
[[1]
 [2]
 [3]
 [4]] 
Вектор має розмір (4, 1)


In [65]:
a = range(1,11,2)
print(list(a))
b = np.arange(1,11)
print("Просто значення від 1 до 10", b)
print(b.shape)
print("Перший елемент масиву = ", b[0])
print("Останній елемент масиву = ", b[-1])

[1, 3, 5, 7, 9]
Просто значення від 1 до 10 [ 1  2  3  4  5  6  7  8  9 10]
(10,)
Перший елемент масиву =  1
Останній елемент масиву =  10


In [66]:
a = range(1,11)
list(a[-1:-5:-1])

[10, 9, 8, 7]

In [67]:
b = np.arange(1,100)
print(b[:])
print("Це питають на всіх інтервю по Пайтону:", b[::-1])
print(b[0:2+1])
print(b[3:6])
#Можна міняти крок, який є третім елементом
print(b[-1:-4:-1])

c = np.array([b[0:3], b[3:6], b[6:9]])
print("Нарізаємо масив по 3 елементи та створюємо матрицю:\n", c)

c = np.array([b[-1:-4:-1], b[-30:-33:-1], b[6:9]])
print("Використовуючи відємні індекси:\n",c)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48
 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71 72
 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95 96
 97 98 99]
Це питають на всіх інтервю по Пайтону: [99 98 97 96 95 94 93 92 91 90 89 88 87 86 85 84 83 82 81 80 79 78 77 76
 75 74 73 72 71 70 69 68 67 66 65 64 63 62 61 60 59 58 57 56 55 54 53 52
 51 50 49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28
 27 26 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10  9  8  7  6  5  4
  3  2  1]
[1 2 3]
[4 5 6]
[99 98 97]
Нарізаємо масив по 3 елементи та створюємо матрицю:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Використовуючи відємні індекси:
 [[99 98 97]
 [70 69 68]
 [ 7  8  9]]


In [68]:
start = 0.04
stop = 1.84
N = (stop - start) / 0.08
print("Теоретично буде мати кількість елементів: ", N)
x = np.arange(start, stop, 0.08)
print(x)
print("Arange згенерував ", len(x), " елементи")
y = x * 2.5
print("Після перемноження:", y)
x = np.arange(0.04, 1.84, 0.08, dtype=np.float32)
print("При збільшенні кількості знаків після коми в нас виникає похибка округлення:\n",x)

print ("Базовий приклад похибки: ", 0.1 + 0.1 + 0.1)

Теоретично буде мати кількість елементів:  22.5
[0.04 0.12 0.2  0.28 0.36 0.44 0.52 0.6  0.68 0.76 0.84 0.92 1.   1.08
 1.16 1.24 1.32 1.4  1.48 1.56 1.64 1.72 1.8 ]
Arange згенерував  23  елементи
Після перемноження: [0.1 0.3 0.5 0.7 0.9 1.1 1.3 1.5 1.7 1.9 2.1 2.3 2.5 2.7 2.9 3.1 3.3 3.5
 3.7 3.9 4.1 4.3 4.5]
При збільшенні кількості знаків після коми в нас виникає похибка округлення:
 [0.04       0.12       0.19999999 0.28       0.35999998 0.43999997
 0.52       0.6        0.68       0.76       0.84       0.92
 1.         1.0799999  1.16       1.2399999  1.3199999  1.4
 1.4799999  1.56       1.6399999  1.7199999  1.8       ]
Базовий приклад похибки:  0.30000000000000004


In [69]:
print("Ми хочемо мати 23 елементи:")
x, step = np.linspace(start, stop, 23, endpoint=True, retstep=True)
print(x)
print("Linspace згенерував ", len(x), " елементи")
print(np.round(x, 2))
print("Крок буде:", step)

Ми хочемо мати 23 елементи:
[0.04       0.12181818 0.20363636 0.28545455 0.36727273 0.44909091
 0.53090909 0.61272727 0.69454545 0.77636364 0.85818182 0.94
 1.02181818 1.10363636 1.18545455 1.26727273 1.34909091 1.43090909
 1.51272727 1.59454545 1.67636364 1.75818182 1.84      ]
Linspace згенерував  23  елементи
[0.04 0.12 0.2  0.29 0.37 0.45 0.53 0.61 0.69 0.78 0.86 0.94 1.02 1.1
 1.19 1.27 1.35 1.43 1.51 1.59 1.68 1.76 1.84]
Крок буде: 0.08181818181818182


In [70]:
examples = {
    'Скаляр': np.array(1), 
    'Вектор Рядок': np.array([1, 2, 3]), 
    'Вектор Стовпець': np.array([[1], [2], [3]]), 
    'Матриця': np.array([[1, 2],[3, 4], [5, 6]]),
    'Багатовимірна Матриця': np.array([ [[111, 112, 000], [121, 122, 000]],
                                        [[211, 212, 000], [221, 222, 000]],
                                        [[311, 312, 000], [321, 322, 000]] ])
    }

for key in examples:
    print(f"Для {key} Значення\n {examples[key]}, \nКількість вимірів {np.ndim(examples[key])}, Форма {examples[key].shape}")


Для Скаляр Значення
 1, 
Кількість вимірів 0, Форма ()
Для Вектор Рядок Значення
 [1 2 3], 
Кількість вимірів 1, Форма (3,)
Для Вектор Стовпець Значення
 [[1]
 [2]
 [3]], 
Кількість вимірів 2, Форма (3, 1)
Для Матриця Значення
 [[1 2]
 [3 4]
 [5 6]], 
Кількість вимірів 2, Форма (3, 2)
Для Багатовимірна Матриця Значення
 [[[111 112   0]
  [121 122   0]]

 [[211 212   0]
  [221 222   0]]

 [[311 312   0]
  [321 322   0]]], 
Кількість вимірів 3, Форма (3, 2, 3)


In [71]:
a = np.array([ [[111, 112], [121, 122]],
               [[211, 212], [221, 222]],
               [[311, 312], [321, 322]] ])

b = np.array([a, a])

print(f"Ми можемо зробити з {np.ndim(a)}-х вимірного масиву \n{a}")
print(f"Ми можемо зробити {np.ndim(b)}-х вимірний масив \n{b} \n В якого буде форма {b.shape}")

Ми можемо зробити з 3-х вимірного масиву 
[[[111 112]
  [121 122]]

 [[211 212]
  [221 222]]

 [[311 312]
  [321 322]]]
Ми можемо зробити 4-х вимірний масив 
[[[[111 112]
   [121 122]]

  [[211 212]
   [221 222]]

  [[311 312]
   [321 322]]]


 [[[111 112]
   [121 122]]

  [[211 212]
   [221 222]]

  [[311 312]
   [321 322]]]] 
 В якого буде форма (2, 3, 2, 2)


In [72]:
A = np.linspace(0, 10, 30)
print(np.ndim(A), A.shape)
print(A)
print(A[1])
print(A[1:5])
print(A[7:10])

1 (30,)
[ 0.          0.34482759  0.68965517  1.03448276  1.37931034  1.72413793
  2.06896552  2.4137931   2.75862069  3.10344828  3.44827586  3.79310345
  4.13793103  4.48275862  4.82758621  5.17241379  5.51724138  5.86206897
  6.20689655  6.55172414  6.89655172  7.24137931  7.5862069   7.93103448
  8.27586207  8.62068966  8.96551724  9.31034483  9.65517241 10.        ]
0.3448275862068966
[0.34482759 0.68965517 1.03448276 1.37931034]
[2.4137931  2.75862069 3.10344828]


In [73]:
B = A.reshape(3, 10)
print(np.ndim(B), B.shape)
print(B)
print("Цілий рядок", B[0])
print("Конкретний елемент", B[0][0]," або ", B[0, 0])
print(B[1, 1:5])
print(B[:, 0])
print(B[:, -1:-3:-1])

2 (3, 10)
[[ 0.          0.34482759  0.68965517  1.03448276  1.37931034  1.72413793
   2.06896552  2.4137931   2.75862069  3.10344828]
 [ 3.44827586  3.79310345  4.13793103  4.48275862  4.82758621  5.17241379
   5.51724138  5.86206897  6.20689655  6.55172414]
 [ 6.89655172  7.24137931  7.5862069   7.93103448  8.27586207  8.62068966
   8.96551724  9.31034483  9.65517241 10.        ]]
Цілий рядок [0.         0.34482759 0.68965517 1.03448276 1.37931034 1.72413793
 2.06896552 2.4137931  2.75862069 3.10344828]
Конкретний елемент 0.0  або  0.0
[3.79310345 4.13793103 4.48275862 4.82758621]
[0.         3.44827586 6.89655172]
[[ 3.10344828  2.75862069]
 [ 6.55172414  6.20689655]
 [10.          9.65517241]]


In [74]:
C = A.reshape(3, 2, 5)
print(np.ndim(C), C.shape)
print(C)
print("Матриця\n", C[0])
print("Вектор\n", C[0, 1])
print("Конкретний елемент", C[0][1][1]," або ", C[0, 1, 1])
print(C[:, :, 0])

3 (3, 2, 5)
[[[ 0.          0.34482759  0.68965517  1.03448276  1.37931034]
  [ 1.72413793  2.06896552  2.4137931   2.75862069  3.10344828]]

 [[ 3.44827586  3.79310345  4.13793103  4.48275862  4.82758621]
  [ 5.17241379  5.51724138  5.86206897  6.20689655  6.55172414]]

 [[ 6.89655172  7.24137931  7.5862069   7.93103448  8.27586207]
  [ 8.62068966  8.96551724  9.31034483  9.65517241 10.        ]]]
Матриця
 [[0.         0.34482759 0.68965517 1.03448276 1.37931034]
 [1.72413793 2.06896552 2.4137931  2.75862069 3.10344828]]
Вектор
 [1.72413793 2.06896552 2.4137931  2.75862069 3.10344828]
Конкретний елемент 2.0689655172413794  або  2.0689655172413794
[[0.         1.72413793]
 [3.44827586 5.17241379]
 [6.89655172 8.62068966]]


In [75]:
#так не робиться, просто для візуалізації витягуємо елементи
for i in range(2):
    print(i, C[0][i][0])

0 0.0
1 1.7241379310344829


In [76]:
o = np.ones([2, 5, 3])
print(o)

z = np.zeros([2, 5, 3])
print(z)

[[[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]]
[[[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]]
