In [ ]:
%pip install numpy

In [ ]:
%time
import numpy as np

temperature = [20.1, 20.1, 20.2, 20.4, 20.8, 30]
print(temperature)

t1 = temperature * 5

print(f"При множенні на 5 маємо: {t1}")

t1 = list()
for x in temperature:
    t1.append(x*5 + 20)

print(f"При множенні на 5 маємо: {t1}, тип даних {type(t1)}")

t1 = [ x*5 + 20 for x in temperature] 
print(f"Тепер отримаємо: {t1}") 

In [ ]:
t2 = np.array(temperature)
print("Масив з використанням методів NumPy", t2," тип даних ", type(t2))

t3 = t2 * 5 + 20
print("При множенні на 5 отримуємо:", t3)
t3 = t2 % 5
print("При множенні на 5 отримуємо:", t3)

In [ ]:
ll = [1, 2, 3, 4, 5]
l2 = [6, 7, 8, 9, 10]
l3 = [11, 12, 13, 14, 15]
vector_1 = np.array(ll)
vector_2 = np.array([ll, l2, l3])
vector_3 = np.array([[ll, l2, l3], [ll, l2, l3],  [ll, l2, l3],  [ll, l2, l3]])

print(f"Це є List {ll}, Масив numpy \n {vector_1},\nМасив numpy \n {vector_2},\nМасив numpy \n {vector_3}")

t1 = vector_1 * 5
t2 = vector_2 * 5
t3 = vector_3 * 5
print(f"Масив numpy \n {t1},\nМасив numpy \n {t2},\nМасив numpy \n {t3}")

In [ ]:
print("\nВектор має розмір", vector_1.shape)
print("\nВектор має розмір", vector_2.shape)
print("\nВектор має розмір", vector_3.shape)

In [ ]:
vector_row = np.array([[1, -5, 3, 2, 4]])
vector_column = np.array([[1], 
                          [2], 
                          [3], 
                          [4]])
print(vector_row, "\nВектор має розмір", vector_row.shape)
print(vector_column, "\nВектор має розмір", vector_column.shape)

In [41]:
a = range(1,11,2)
print(list(a))
b = np.arange(1,11)
print("Просто значення від 1 до 10", b)
print(b.shape)
print("Перший елемент масиву = ", b[0])
print("Останній елемент масиву = ", b[-1])

[1, 3, 5, 7, 9]
Просто значення від 1 до 10 [ 1  2  3  4  5  6  7  8  9 10]
(10,)
Перший елемент масиву =  1
Останній елемент масиву =  10


In [52]:
a = range(1,11)
list(a[-1:-5:-1])

[10, 9, 8, 7]

In [62]:
b = np.arange(1,100)
print(b[:])
print("Це питають на всіх інтервю оп Пайтону:", b[::-1])
print(b[0:2+1])
print(b[3:6])
#Можна міняти крок, який є третім елементом
print(b[-1:-4:-1])

c = np.array([b[0:3], b[3:6], b[6:9]])
print("Нарізаємо масив по 3 елементи та створюємо матрицю:\n", c)

c = np.array([b[-1:-4:-1], b[-30:-33:-1], b[6:9]])
print("Використовуючи відємні індекси:\n",c)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48
 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71 72
 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95 96
 97 98 99]
Це питають на всіх інтервю оп Пайтону: [99 98 97 96 95 94 93 92 91 90 89 88 87 86 85 84 83 82 81 80 79 78 77 76
 75 74 73 72 71 70 69 68 67 66 65 64 63 62 61 60 59 58 57 56 55 54 53 52
 51 50 49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28
 27 26 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10  9  8  7  6  5  4
  3  2  1]
[1 2 3]
[4 5 6]
[99 98 97]
Нарізаємо масив по 3 елементи та створюємо матрицю:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Використовуючи відємні індекси:
 [[99 98 97]
 [70 69 68]
 [ 7  8  9]]


In [89]:
start = 0.04
stop = 1.84
N = (stop - start) / 0.08
print("Теоретично буде мати кількість елементів: ", N)
x = np.arange(start, stop, 0.08)
print(x)
print("Arange згенерував ", len(x), " елементи")
y = x * 2.5
print("Після перемноження:", y)
x = np.arange(0.04, 1.84, 0.08, dtype=np.float32)
print("При збільшенні кількості знаків після коми в нас виникає похибка округлення:\n",x)

print ("Базовий приклад похибки: ", 0.1 + 0.1 + 0.1)

Теоретично буде мати кількість елементів:  22.5
[0.04 0.12 0.2  0.28 0.36 0.44 0.52 0.6  0.68 0.76 0.84 0.92 1.   1.08
 1.16 1.24 1.32 1.4  1.48 1.56 1.64 1.72 1.8 ]
Arange згенерував  23  елементи
Після перемноження: [0.1 0.3 0.5 0.7 0.9 1.1 1.3 1.5 1.7 1.9 2.1 2.3 2.5 2.7 2.9 3.1 3.3 3.5
 3.7 3.9 4.1 4.3 4.5]
При збільшенні кількості знаків після коми в нас виникає похибка округлення:
 [0.04       0.12       0.19999999 0.28       0.35999998 0.43999997
 0.52       0.6        0.68       0.76       0.84       0.92
 1.         1.0799999  1.16       1.2399999  1.3199999  1.4
 1.4799999  1.56       1.6399999  1.7199999  1.8       ]
Базовий приклад похибки:  0.30000000000000004


In [91]:
print("Ми хочемо мати 23 елементи:")
x, step = np.linspace(start, stop, 23, endpoint=True, retstep=True)
print(x)
print("Linspace згенерував ", len(x), " елементи")
print(np.round(x, 2))
print("Крок буде:", step)


Ми хочемо мати 23 елементи:
[0.04       0.12181818 0.20363636 0.28545455 0.36727273 0.44909091
 0.53090909 0.61272727 0.69454545 0.77636364 0.85818182 0.94
 1.02181818 1.10363636 1.18545455 1.26727273 1.34909091 1.43090909
 1.51272727 1.59454545 1.67636364 1.75818182 1.84      ]
Linspace згенерував  23  елементи
[0.04 0.12 0.2  0.29 0.37 0.45 0.53 0.61 0.69 0.78 0.86 0.94 1.02 1.1
 1.19 1.27 1.35 1.43 1.51 1.59 1.68 1.76 1.84]
Крок буде: 0.08181818181818182
